- apps/web/assets/stylesheets/_highlight.scss
- apps/web/assets/stylesheets/main.scss
> Add github color scheme

- Gemfile
- Gemfile.lock
- spec/admin/controllers/moderation/update_spec.rb
- spec/admin/controllers/tasks/edit_spec.rb
- spec/admin/controllers/tasks/show_spec.rb
- spec/admin/controllers/tasks/update_spec.rb
- spec/admin/controllers/users/destroy_spec.rb
- spec/admin/controllers/users/edit_spec.rb
- spec/admin/controllers/users/show_spec.rb
- spec/admin/controllers/users/update_spec.rb
- spec/admin/views/moderation/index_spec.rb
- spec/admin/views/tasks/index_spec.rb
- spec/admin/views/users/index_spec.rb
- spec/auth/controllers/sessions/create_spec.rb
- spec/fabricators/task_fabricator.rb
- spec/fabricators/user_fabricator.rb
- spec/ossboard/repositories/task_repository_spec.rb
- spec/ossboard/repositories/user_repository_spec.rb
- spec/spec_helper.rb
- spec/web/controllers/task_status/update_spec.rb
- spec/web/controllers/tasks/create_spec.rb
- spec/web/controllers/tasks/edit_spec.rb
- spec/web/controllers/tasks/index_spec.rb
- spec/web/controllers/tasks/show_spec.rb
- spec/web/controllers/tasks/update_spec.rb
- spec/web/controllers/users/show_spec.rb
- spec/web/views/main/index_spec.rb
> Use fabrication gem in all tests

- apps/admin/controllers/tasks/update.rb
- apps/admin/templates/tasks/index.html.slim
- apps/admin/templates/tasks/show.html.slim
- apps/admin/views/tasks/edit.rb
- apps/admin/views/tasks/index.rb
- apps/admin/views/tasks/show.rb
- apps/web/assets/javascripts/main.js
- apps/web/controllers/tasks/create.rb
- apps/web/controllers/tasks/update.rb
- apps/web/views/tasks/new.rb
- db/migrations/20170103074521_add_repository_name_to_tasks.rb
- lib/ossboard/services/github_issue_requester.rb
- spec/admin/controllers/tasks/update_spec.rb
- spec/api/controllers/issue/show_spec.rb
- spec/fabricators/task_fabricator.rb
- spec/ossboard/services/github_issue_requester_spec.rb
- spec/web/controllers/tasks/create_spec.rb
- spec/web/controllers/tasks/update_spec.rb
Solution of https://github.com/davydovanton/ossboard/issues/10
> add repository to tasks

- apps/admin/controllers/tasks/update.rb
- apps/admin/templates/tasks/show.html.slim
- apps/admin/views/application_layout.rb
- apps/admin/views/tasks/edit.rb
- apps/admin/views/tasks/show.rb
- apps/web/controllers/tasks/create.rb
- apps/web/views/application_layout.rb
- apps/web/views/tasks/new.rb
- db/migrations/20161230053051_add_complexity_to_tasks.rb
- spec/admin/controllers/tasks/update_spec.rb
- spec/fabricators/task_fabricator.rb
- spec/web/controllers/tasks/create_spec.rb
> Add 'complexity' attribute for tasks

- apps/api/config/routes.rb
- apps/api/controllers/md_preview/create.rb
- apps/web/assets/javascripts/main.js
- apps/web/assets/stylesheets/_load_animation.scss
- apps/web/assets/stylesheets/_tasks.scss
- apps/web/assets/stylesheets/main.scss
- apps/web/views/tasks/new.rb
- spec/api/controllers/md_preview/create_spec.rb
> Preview md text in tasks#new page

- Gemfile
I get an error when trying to run `hanami server`:
```
$ bundle exec hanami server
bundler: failed to load command: hanami
(/Users/mgrachev/dev/ossboard/vendor/bundle/bin/hanami)
LoadError: cannot load such file -- false
```
> Fix Gemfile

- apps/web/assets/stylesheets/_tasks.scss
this is just a fix of div collision form for issue https://github.com/davydovanton/ossboard/issues/39.
But I think there are no problem in new design https://github.com/davydovanton/ossboard/issues/11
> fix collision

- lib/ossboard/matchers/git_host_matcher.rb
- spec/ossboard/matchers/git_host_matcher_spec.rb
> Fix git host matcher in case of url with dots

- apps/web/assets/javascripts/main.js
- apps/web/assets/stylesheets/_tasks.scss
- apps/web/templates/tasks/index.html.slim
- apps/web/views/tasks/index.rb
- spec/web/views/tasks/index_spec.rb
> Tasks page: create status select instead list

- apps/web/templates/tasks/new.html.slim
- apps/web/views/tasks/new.rb
- spec/web/views/tasks/new_spec.rb
Fix for https://github.com/ossboard-org/ossboard/issues/40
> fix md body validation message

- apps/admin/views/tasks/edit.rb
- apps/web/assets/javascripts/main.js
- apps/web/assets/stylesheets/_tasks.scss
- apps/web/controllers/tasks/index.rb
- apps/web/templates/tasks/index.html.slim
- apps/web/views/tasks/index.rb
- lib/ossboard/entities/task.rb
- lib/ossboard/repositories/task_repository.rb
- spec/ossboard/repositories/task_repository_spec.rb
- spec/web/controllers/tasks/index_spec.rb
- spec/web/views/tasks/index_spec.rb
[Issue](https://github.com/ossboard-org/ossboard/issues/64)
> Create language filter on tasks page

- apps/web/assets/javascripts/main.js
- apps/web/controllers/tasks/index.rb
- apps/web/templates/tasks/index.html.slim
- apps/web/views/tasks/index.rb
- lib/ossboard/repositories/task_repository.rb
- spec/ossboard/repositories/task_repository_spec.rb
- spec/web/controllers/tasks/index_spec.rb
- spec/web/views/tasks/index_spec.rb
1. we don't use data from entity and use again existed data
2. we added strange and ugly validation to repository object
3. we checked action implementation in repository object
4. DRY in js
> Refactoring tasks#index action in web application

- .rspec
- apps/web/assets/javascripts/main.js
- lib/ossboard/services/github_issue_requester.rb
- lib/ossboard/services/gitlab_issue_requester.rb
- spec/admin/controllers/users/edit_spec.rb
- spec/api/controllers/issue/show_spec.rb
- spec/cassettes/github_failed_issue.yml
- spec/cassettes/github_success_issue.yml
- spec/cassettes/gitlab_failed_issue.yml
- spec/cassettes/gitlab_success_issue.yml
- spec/cassettes/gitlab_unathorized_issue.yml
- spec/ossboard/services/github_issue_requester_spec.rb
- spec/ossboard/services/gitlab_issue_requester_spec.rb
- spec/web/controllers/tasks/update_spec.rb
Solve https://github.com/ossboard-org/ossboard/issues/65
1. Detect complexity level if export from gitlab/github
2. Random order tests by default
3. Some fixes of random falling tests.
> add complexity level export from issues

- Gemfile
- Gemfile.lock
- config/initializers/monads.rb
- lib/ossboard/services/github_issue_requester.rb
- lib/ossboard/services/gitlab_issue_requester.rb
- spec/cassettes/github_success_issue_without_labels.yml
- spec/cassettes/gitlab_success_issue_without_labels.yml
- spec/ossboard/services/github_issue_requester_spec.rb
- spec/ossboard/services/gitlab_issue_requester_spec.rb
1. Added new specs for issues without complexity labels
2. Used [dry-monads](http://dry-rb.org/gems/dry-monads/) instead tuples for better understanding and dropping all unnecessary conditions
Reference to https://github.com/ossboard-org/ossboard/pull/85
> Refactoring #85

- apps/web/templates/application.html.slim
Solving https://github.com/ossboard-org/ossboard/issues/69
> fix footer

- db/migrations/20170214010900_create_points.rb
- lib/ossboard/entities/point.rb
- lib/ossboard/repositories/point_repository.rb
- lib/ossboard/repositories/user_repository.rb
- lib/ossboard/services/points_calculator.rb
- lib/ossboard/workers/calculate_points_worker.rb
- spec/ossboard/entities/point_spec.rb
- spec/ossboard/repositories/point_repository_spec.rb
- spec/ossboard/services/points_calculator_spec.rb
- spec/ossboard/workers/calculate_points_worker_spec.rb
I created the simple worker for calculating all user points. After that PR we can update `/leaderboards` page with real data
> Calculate user points for leaderboard

- .gitignore
- spec/ossboard/workers/calculate_points_worker_spec.rb
- spec/web/controllers/tasks/index_spec.rb
1. Fix for random falling test caused by not cleared Task repository
2. Fix Travis CI falling build caused by missing `log/` folder
> fix random falling test. fix falling travis build

- spec/ossboard/repositories/user_repository_spec.rb
fix falling test.
to reproduce `rspec './spec/ossboard/repositories/user_repository_spec.rb[1:3:2]' './spec/web/controllers/tasks/update_spec.rb[1:2:3]' --seed 25495`
> fix random falling tests

- apps/web/assets/stylesheets/_tasks.scss
- config/initializers/markdown.rb
- spec/support/markdown/text.html
- spec/support/markdown/text.md
- spec/web/features/tasks_spec.rb
process checkbox in md description #104
> markdown checkboxes

- apps/web/controllers/tasks/create.rb
- lib/ossboard/interactors/tasks/create.rb
- spec/web/controllers/tasks/create_spec.rb
Reference to https://github.com/ossboard-org/ossboard/issues/131
> Add create task interactor

- lib/container.rb
```
LoadError: cannot load such file -- ossboard/matchers/git_host_matcher
```
> Fix run hanami server

- spec/admin/controllers/users/destroy_spec.rb
- spec/admin/views/users/index_spec.rb
- spec/ossboard/services/points_calculator_spec.rb
```
bundle exec rspec --seed 6964
Failures:
1) Services::PointsCalculator#perform when user complete tasks and tasks with different status calculates points
Failure/Error: expect(point.developer).to eq 11
expected: 11
got: 14
(compared using ==)
Finished in 33.7 seconds (files took 4.76 seconds to load)
443 examples, 1 failure, 2 pending
Failed examples:
rspec ./spec/ossboard/services/points_calculator_spec.rb:101 # Services::PointsCalculator#perform when user complete tasks and tasks with different status calculates points
Randomized with seed 6964
```
```
Failures:
1) Admin::Views::Users::Index#banned_users should eq []
Failure/Error: it { expect(view.banned_users).to eq [] }
expected: []
got: ["anton"]
(compared using ==)
Finished in 15.56 seconds (files took 10.09 seconds to load)
443 …
```
> Fix floating tests

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- spec/support/database_cleaner.rb
> add database cleaner

- lib/ossboard/interactors/task_status/update.rb
- spec/web/controllers/task_status/update_spec.rb
Fixed https://github.com/ossboard-org/ossboard/issues/109
> Trim invalid chars in assigned username

- Gemfile
- Gemfile.lock
- apps/admin/controllers/tasks/update.rb
- lib/ossboard/interactors/tasks/update.rb
Hide update logic into Hanami Interactor
> updating tasks using interactor

- Gemfile
- apps/admin/controllers/tasks/update.rb
- apps/admin/controllers/users/update.rb
- spec/admin/controllers/tasks/update_spec.rb
- spec/admin/controllers/users/update_spec.rb
This is temporary fix of #162 , i.e. it will take some time fix problem correctly for me. This fix prevents from 500, but do not show fields with errors
> Temporary fixes 500 (users and tasks updating)

- .gitignore
- spec/cassettes/github_success_issue_without_complexity.yml
- spec/ossboard/interactors/issues/show_spec.rb
- spec/ossboard/interactors/task_status/update_spec.rb
- spec/ossboard/interactors/tasks/create_spec.rb
- spec/ossboard/interactors/tasks/update_spec.rb
> Add specs for interactors

- .gitignore
- apps/admin/controllers/users/update.rb
- lib/ossboard/interactors/users/update.rb
> Updating users using interactor

- lib/ossboard/entities/task.rb
- spec/web/controllers/tasks/index_spec.rb
- spec/web/views/tasks/index_spec.rb
Purpose of this PR: Fixes issue #179. Respective test case also was added.
> fix filtering tasks by language

- apps/web/assets/stylesheets/_labels.scss
- apps/web/assets/stylesheets/_tasks.scss
- apps/web/controllers/tasks/create.rb
- apps/web/templates/tasks/index.html.slim
- apps/web/templates/tasks/show.html.slim
- apps/web/views/tasks/index.rb
- apps/web/views/tasks/new.rb
- apps/web/views/tasks/show.rb
- db/migrations/20171013101305_add_firt_pr_field_to_tasks.rb
- lib/ossboard/entities/task.rb
- lib/ossboard/repositories/task_repository.rb
- spec/fabricators/task_fabricator.rb
- spec/web/controllers/tasks/create_spec.rb
- spec/web/features/tasks_spec.rb
Good evening! I complete #176 task, can you review my code, and give me advice on how I can improve it? Thanks!
> Add 'Good for first PR flag'
